[package]
name = "illuminate-log"
description = "The Illuminate Log package."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
illuminate-support.workspace = true
illuminate-container.workspace = true
illuminate-config.workspace = true
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
