[package]
name = "illuminate-validation"
description = "The Illuminate Validation package."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
illuminate-support.workspace = true
illuminate-container.workspace = true
illuminate-http.workspace = true
illuminate-routing.workspace = true
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true
regex.workspace = true
async-trait.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
uuid.workspace = true
ulid.workspace = true
mime_guess.workspace = true
thiserror.workspace = true
anyhow.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
