[package]
name = "illuminate-broadcasting"
description = "The Illuminate Broadcasting package: broadcast your server-side events to your JavaScript application."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
illuminate-support.workspace = true
illuminate-container.workspace = true
illuminate-config.workspace = true
illuminate-http.workspace = true
illuminate-routing.workspace = true
illuminate-events.workspace = true
illuminate-queue.workspace = true
illuminate-auth.workspace = true
illuminate-http-client.workspace = true
illuminate-log.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
tokio.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
md-5.workspace = true
base64.workspace = true
rand.workspace = true
regex.workspace = true
indexmap.workspace = true
futures.workspace = true
