[package]
name = "illuminate-events"
description = "The Illuminate Events package."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
illuminate-support.workspace = true
illuminate-container.workspace = true
async-trait.workspace = true
futures.workspace = true
indexmap.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
