[package]
name = "illuminate-view"
description = "The Illuminate View package, featuring the Blade templating engine."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
illuminate-support.workspace = true
illuminate-container.workspace = true
illuminate-config.workspace = true
illuminate-http.workspace = true
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
