//! The `Model` trait: Eloquent's active record API.

use std::future::Future;

use illuminate_pagination::{LengthAwarePaginator, Paginator};
use illuminate_support::{Carbon, Collection, Map, Result, Str, Value, ValueExt};

use super::builder::Builder;
use super::errors::{MassAssignmentException, ModelNotFoundException};
use super::events::{self, EventOutcome, ModelEvent, Observer, fire};
use super::original::{self, IntoAttributeNames, Original, has_changes, is_equivalent};
use super::relations::{
    BelongsTo, BelongsToMany, DynRelation, EagerSpec, HasMany, HasManyThrough, HasOne,
    HasOneThrough, MorphMany, MorphOne, MorphTo, MorphToMany,
};
use super::scope::{Scope, scope_name};
use super::state::{self, EloquentState};
use super::{Attributes, BoxFuture, IntoIds, IntoRelations, KeyType, UniqueIds};
use crate::expression::{Ident, Operand};
use crate::query::{Builder as QueryBuilder, WhereInValues};
use crate::{Connection, DatabaseManager};

/// An Eloquent model.
///
/// Implement it with `#[derive(Model)]`; the derive generates the required
/// items (the table, keys, attribute conversions and relation loaders) and
/// every other method is provided. See the [module docs](super) for an
/// overview.
///
/// Async methods return `Send` futures, so they can be used anywhere in
/// the framework (route handlers, jobs, spawned tasks).
pub trait Model: Send + Sync + Clone + Sized + 'static {
    // ------------------------------------------------------------------
    // Required: generated by #[derive(Model)]
    // ------------------------------------------------------------------

    /// The table associated with the model (`users` for `User`).
    fn table() -> String;

    /// The model's class name (`User`).
    fn class_name() -> &'static str;

    /// The primary key column.
    fn primary_key() -> &'static str;

    /// The type of the primary key.
    fn key_type() -> KeyType;

    /// Whether the primary key is auto-incrementing.
    fn incrementing() -> bool;

    /// Whether `created_at` / `updated_at` are maintained automatically.
    fn timestamps() -> bool;

    /// Whether the model has a `created_at` column.
    fn uses_created_at() -> bool;

    /// Whether the model has an `updated_at` column.
    fn uses_updated_at() -> bool;

    /// The connection the model uses (`None` for the default connection).
    fn connection_name() -> Option<&'static str>;

    /// The attributes that are mass assignable.
    fn fillable() -> &'static [&'static str];

    /// The attributes that aren't mass assignable (`["*"]` guards everything).
    fn guarded() -> &'static [&'static str];

    /// The attributes hidden from serialization.
    fn hidden() -> &'static [&'static str];

    /// The attributes visible in serialization (empty means "all").
    fn visible() -> &'static [&'static str];

    /// The accessors appended to the model's array form.
    fn appends() -> &'static [&'static str];

    /// The number of models to return per page.
    fn per_page() -> u64;

    /// The column used for route model binding.
    fn route_key_name() -> &'static str;

    /// Whether the model is soft deletable.
    fn soft_deletes() -> bool;

    /// The unique ids generated for new models' keys.
    fn unique_ids() -> UniqueIds;

    /// The attributes hashed when the model is saved.
    fn hashed_attributes() -> &'static [&'static str];

    /// The persisted columns.
    fn columns() -> &'static [&'static str];

    /// The eager loadable relationships.
    fn relation_names() -> &'static [&'static str];

    /// A new, empty instance (every field at its default).
    fn template() -> Self;

    /// The persisted attributes, in storage format.
    fn to_attributes(&self) -> Map<String, Value>;

    /// Hydrate a model from a database row.
    fn from_attributes(attributes: Map<String, Value>) -> Result<Self>;

    /// The model's array form, respecting hidden / visible attributes,
    /// appended accessors and loaded relationships.
    fn to_array(&self) -> Map<String, Value>;

    /// Get an attribute (or appended accessor) by name.
    fn get_attribute(&self, key: &str) -> Value;

    /// Set an attribute by name, casting the value to the field's type.
    /// Unknown attributes are ignored.
    fn set_attribute(&mut self, key: &str, value: Value) -> Result<()>;

    /// Eager load a relationship onto the models.
    fn eager_load<'a>(
        models: &'a mut [Self],
        relation: &'a str,
        spec: EagerSpec,
    ) -> BoxFuture<'a, Result<()>>;

    /// The type-erased relationship with the given name.
    fn relation(name: &str) -> Option<Box<dyn DynRelation>>;

    /// Boot the model: called once, before the model is first used.
    fn boot() {}

    /// The names of the relationships currently loaded on the model.
    fn loaded_relations(&self) -> Vec<&'static str> {
        Vec::new()
    }

    /// The model's [`Original`] attributes tracker: generated for models
    /// with an `Original` field, `None` otherwise.
    fn original_state(&self) -> Option<&Original> {
        None
    }

    /// The model's [`Original`] attributes tracker, mutably.
    fn original_state_mut(&mut self) -> Option<&mut Original> {
        None
    }

    /// Unset a loaded relationship (generated for models with `#[relation]`
    /// fields).
    fn unset_relation(&mut self, name: &str) {
        let _ = name;
    }

    /// Unset every loaded relationship (generated for models with
    /// `#[relation]` fields).
    fn unset_relations(&mut self) {}

    /// Save every loaded related model, recursively (generated for models
    /// with `#[relation]` fields; used by [`push`](Model::push)).
    fn push_relations<'a>(&'a mut self) -> BoxFuture<'a, Result<bool>> {
        Box::pin(async { Ok(true) })
    }

    // ------------------------------------------------------------------
    // Conventions
    // ------------------------------------------------------------------

    /// The "created at" column.
    fn created_at_column() -> &'static str {
        "created_at"
    }

    /// The "updated at" column.
    fn updated_at_column() -> &'static str {
        "updated_at"
    }

    /// The "deleted at" column used by soft deletes.
    fn deleted_at_column() -> &'static str {
        "deleted_at"
    }

    /// Whether the model maintains its timestamps right now: it has them,
    /// and isn't inside [`without_timestamps`](Model::without_timestamps).
    fn uses_timestamps() -> bool {
        Self::timestamps() && !state::is_ignoring_timestamps::<Self>()
    }

    /// Run the future without the model maintaining its `created_at` /
    /// `updated_at` timestamps (Laravel's `Model::withoutTimestamps`).
    ///
    /// ```ignore
    /// User::without_timestamps(async { user.save().await }).await?;
    /// ```
    fn without_timestamps<F: Future + Send>(future: F) -> impl Future<Output = F::Output> + Send
    where
        F::Output: Send,
    {
        state::without_timestamps_for::<Self, F>(future)
    }

    /// Determine whether the model is currently ignoring its timestamps.
    fn is_ignoring_timestamps() -> bool {
        state::is_ignoring_timestamps::<Self>()
    }

    /// A fresh timestamp for the model.
    fn fresh_timestamp() -> Carbon {
        Carbon::now()
    }

    /// A fresh timestamp for the model, in storage format.
    fn fresh_timestamp_string() -> String {
        Carbon::now().to_date_time_string()
    }

    /// Set the `updated_at` timestamp (and `created_at` for new models)
    /// to now, unless they were set by hand.
    fn update_timestamps(&mut self) -> Result<&mut Self> {
        if !Self::uses_timestamps() {
            return Ok(self);
        }
        let time = now();
        let set_by_hand = !self.get_attribute(Self::updated_at_column()).is_null()
            && self.is_dirty_any(Self::updated_at_column());
        if Self::uses_updated_at() && !set_by_hand {
            self.set_attribute(Self::updated_at_column(), time.clone())?;
        }
        if !self.exists()
            && Self::uses_created_at()
            && self.get_attribute(Self::created_at_column()).is_null()
        {
            self.set_attribute(Self::created_at_column(), time)?;
        }
        Ok(self)
    }

    /// The default foreign key name for the model (`user_id`).
    fn get_foreign_key() -> String {
        format!("{}_{}", Str::snake(Self::class_name()), Self::primary_key())
    }

    /// The table-qualified primary key (`users.id`).
    fn get_qualified_key_name() -> String {
        format!("{}.{}", Self::table(), Self::primary_key())
    }

    /// The class name stored in polymorphic `*_type` columns (see
    /// [`morph_map`](super::morph_map)).
    fn morph_class() -> String {
        EloquentState::resolve().morph_alias(Self::class_name())
    }

    /// Get the database connection for the model.
    fn get_connection() -> Connection {
        let manager = DatabaseManager::resolve();
        match Self::connection_name() {
            Some(name) => manager.connection(name),
            None => manager.default_connection(),
        }
    }

    // ------------------------------------------------------------------
    // Querying
    // ------------------------------------------------------------------

    /// Begin querying the model.
    fn query() -> Builder<Self> {
        Builder::new()
    }

    /// Begin querying the model on the write connection.
    fn on_write_connection() -> Builder<Self> {
        Self::query().use_write_pdo()
    }

    /// The conventional pivot table joining the model with `R`: both snake
    /// cased model names, in alphabetical order (`role_user`).
    fn joining_table<R: Model>() -> String {
        let mut segments = [Str::snake(Self::class_name()), Str::snake(R::class_name())];
        segments.sort();
        segments.join("_")
    }

    /// Begin querying the model on the given connection.
    fn on(connection: &str) -> Builder<Self> {
        Builder::on(connection)
    }

    /// Get all of the models from the database.
    fn all() -> impl Future<Output = Result<Collection<Self>>> + Send {
        async { Self::query().get().await }
    }

    /// Find a model by its primary key.
    fn find(id: impl Into<Value> + Send) -> impl Future<Output = Result<Option<Self>>> + Send {
        async move { Self::query().find(id).await }
    }

    /// Find a model by its primary key or fail with a [`ModelNotFoundException`].
    fn find_or_fail(id: impl Into<Value> + Send) -> impl Future<Output = Result<Self>> + Send {
        async move { Self::query().find_or_fail(id).await }
    }

    /// Find models by their primary keys.
    fn find_many(
        ids: impl IntoIds + Send,
    ) -> impl Future<Output = Result<Collection<Self>>> + Send {
        async move { Self::query().find_many(ids).await }
    }

    /// Find a model by its primary key or return a new instance.
    fn find_or_new(id: impl Into<Value> + Send) -> impl Future<Output = Result<Self>> + Send {
        async move { Ok(Self::query().find(id).await?.unwrap_or_else(Self::template)) }
    }

    /// Get the first model matching a basic where clause.
    fn first_where(
        column: impl Into<Ident> + Send,
        value: impl Into<Operand> + Send,
    ) -> impl Future<Output = Result<Option<Self>>> + Send {
        async move { Self::query().where_(column, value).first().await }
    }

    /// Create and save a new model, respecting mass assignment protection.
    ///
    /// ```ignore
    /// let user = User::create(json!({"name": "Taylor", "email": "taylor@laravel.com"})).await?;
    /// ```
    fn create(
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        async move {
            let mut model = Self::template();
            model.fill(attributes)?;
            model.save().await?;
            Ok(model)
        }
    }

    /// Create and save a new model without firing any events.
    fn create_quietly(
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        state::without_events(Self::create(attributes))
    }

    /// Create and save a new model, ignoring mass assignment protection and
    /// without firing any events.
    fn force_create_quietly(
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        state::without_events(Self::force_create(attributes))
    }

    /// Find a model by its primary key, or call the callback when there is
    /// none.
    fn find_or<F, Fut, E>(
        id: impl Into<Value> + Send,
        callback: F,
    ) -> impl Future<Output = Result<Self>> + Send
    where
        F: FnOnce() -> Fut + Send,
        Fut: Future<Output = std::result::Result<Self, E>> + Send,
        E: Into<illuminate_support::Error>,
    {
        async move { Self::query().find_or(id, callback).await }
    }

    /// Permanently delete the models with the given keys (even soft
    /// deletable ones), firing their events.
    fn force_destroy(ids: impl IntoIds + Send) -> impl Future<Output = Result<u64>> + Send {
        async move {
            let ids = ids.into_ids();
            if ids.is_empty() {
                return Ok(0);
            }
            let mut count = 0;
            for mut model in Self::query()
                .with_trashed()
                .find_many(ids)
                .await?
                .into_vec()
            {
                if model.force_delete().await? {
                    count += 1;
                }
            }
            Ok(count)
        }
    }

    /// Create and save a new model, ignoring mass assignment protection.
    fn force_create(
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        async move {
            let mut model = Self::template();
            model.force_fill(attributes)?;
            model.save().await?;
            Ok(model)
        }
    }

    /// Get the first model matching the attributes, or create it with the
    /// attributes merged with the values.
    fn first_or_create(
        attributes: impl Into<Attributes> + Send,
        values: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        async move { Self::query().first_or_create(attributes, values).await }
    }

    /// Get the first model matching the attributes, or instantiate (without
    /// saving) a new one.
    fn first_or_new(
        attributes: impl Into<Attributes> + Send,
        values: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        async move { Self::query().first_or_new(attributes, values).await }
    }

    /// Update the first model matching the attributes with the values, or
    /// create it.
    fn update_or_create(
        attributes: impl Into<Attributes> + Send,
        values: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<Self>> + Send {
        async move { Self::query().update_or_create(attributes, values).await }
    }

    /// Delete the models with the given keys (firing their events),
    /// returning how many were deleted.
    fn destroy(ids: impl IntoIds + Send) -> impl Future<Output = Result<u64>> + Send {
        async move {
            let ids = ids.into_ids();
            if ids.is_empty() {
                return Ok(0);
            }
            let mut count = 0;
            for mut model in Self::query().find_many(ids).await?.into_vec() {
                if model.delete().await? {
                    count += 1;
                }
            }
            Ok(count)
        }
    }

    /// Begin a query eager loading the relationships.
    fn with(relations: impl IntoRelations) -> Builder<Self> {
        Self::query().with(relations)
    }

    /// Begin a query counting the related models (`{relation}_count`).
    fn with_count(relations: impl IntoRelations) -> Builder<Self> {
        Self::query().with_count(relations)
    }

    /// Begin a query for models that have the relationship.
    fn has(relation: &str) -> Builder<Self> {
        Self::query().has(relation)
    }

    /// Begin a query for models whose relationship matches the constraint.
    fn where_has(
        relation: &str,
        constraint: impl FnOnce(QueryBuilder) -> QueryBuilder,
    ) -> Builder<Self> {
        Self::query().where_has(relation, constraint)
    }

    /// Begin a query for models without the relationship.
    fn doesnt_have(relation: &str) -> Builder<Self> {
        Self::query().doesnt_have(relation)
    }

    /// Begin a query with a basic `=` where clause.
    fn where_(column: impl Into<Ident>, value: impl Into<Operand>) -> Builder<Self> {
        Self::query().where_(column, value)
    }

    /// Begin a query with a where clause using an operator.
    fn where_op(
        column: impl Into<Ident>,
        operator: &str,
        value: impl Into<Operand>,
    ) -> Builder<Self> {
        Self::query().where_op(column, operator, value)
    }

    /// Begin a query with a "where in" clause.
    fn where_in(column: impl Into<Ident>, values: impl WhereInValues) -> Builder<Self> {
        Self::query().where_in(column, values)
    }

    /// Begin a query with a "where null" clause.
    fn where_null(column: impl Into<Ident>) -> Builder<Self> {
        Self::query().where_null(column.into())
    }

    /// Begin a query with a "where not null" clause.
    fn where_not_null(column: impl Into<Ident>) -> Builder<Self> {
        Self::query().where_not_null(column.into())
    }

    /// Begin a query selecting the given columns.
    fn select(columns: impl crate::IntoColumns) -> Builder<Self> {
        Self::query().select(columns)
    }

    /// Begin a query ordered by the "created at" column, newest first.
    fn latest() -> Builder<Self> {
        Self::query().latest()
    }

    /// Begin a query ordered by the "created at" column, oldest first.
    fn oldest() -> Builder<Self> {
        Self::query().oldest()
    }

    /// Begin an ordered query.
    fn order_by(column: impl Into<Ident>, direction: &str) -> Builder<Self> {
        Self::query().order_by(column, direction)
    }

    /// Begin a query limited to the given number of models.
    fn limit(value: i64) -> Builder<Self> {
        Self::query().limit(value)
    }

    /// Begin a query including soft deleted models.
    fn with_trashed() -> Builder<Self> {
        Self::query().with_trashed()
    }

    /// Begin a query for only soft deleted models.
    fn only_trashed() -> Builder<Self> {
        Self::query().only_trashed()
    }

    /// Begin a query without the named global scope.
    fn without_global_scope(name: &str) -> Builder<Self> {
        Self::query().without_global_scope(name)
    }

    /// Begin a query without any global scopes.
    fn without_global_scopes() -> Builder<Self> {
        Self::query().without_global_scopes()
    }

    /// Get the first model.
    fn first() -> impl Future<Output = Result<Option<Self>>> + Send {
        async { Self::query().first().await }
    }

    /// Get every model (alias of [`all`](Model::all)).
    fn get() -> impl Future<Output = Result<Collection<Self>>> + Send {
        async { Self::query().get().await }
    }

    /// Count the models.
    fn count() -> impl Future<Output = Result<i64>> + Send {
        async { Self::query().count().await }
    }

    /// Get a column's values.
    fn pluck(
        column: impl Into<Ident> + Send,
    ) -> impl Future<Output = Result<Collection<Value>>> + Send {
        async move { Self::query().pluck(column).await }
    }

    /// Paginate the models (`None` uses the model's `per_page`).
    fn paginate(
        per_page: impl Into<Option<u64>> + Send,
    ) -> impl Future<Output = Result<LengthAwarePaginator<Self>>> + Send {
        async move { Self::query().paginate(per_page).await }
    }

    /// Paginate the models without counting the total.
    fn simple_paginate(
        per_page: impl Into<Option<u64>> + Send,
    ) -> impl Future<Output = Result<Paginator<Self>>> + Send {
        async move { Self::query().simple_paginate(per_page).await }
    }

    // ------------------------------------------------------------------
    // Events and scopes
    // ------------------------------------------------------------------

    /// Register an observer.
    fn observe(observer: impl Observer<Self>) {
        events::observe::<Self, _>(observer);
    }

    /// Listen for the `retrieved` event.
    fn retrieved<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Retrieved, callback);
    }

    /// Listen for the `creating` event (return `false` to cancel).
    fn creating<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Creating, callback);
    }

    /// Listen for the `created` event.
    fn created<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Created, callback);
    }

    /// Listen for the `updating` event (return `false` to cancel).
    fn updating<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Updating, callback);
    }

    /// Listen for the `updated` event.
    fn updated<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Updated, callback);
    }

    /// Listen for the `saving` event (return `false` to cancel).
    fn saving<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Saving, callback);
    }

    /// Listen for the `saved` event.
    fn saved<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Saved, callback);
    }

    /// Listen for the `deleting` event (return `false` to cancel).
    fn deleting<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Deleting, callback);
    }

    /// Listen for the `deleted` event.
    fn deleted<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Deleted, callback);
    }

    /// Listen for the `restoring` event (return `false` to cancel).
    fn restoring<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Restoring, callback);
    }

    /// Listen for the `restored` event.
    fn restored<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Restored, callback);
    }

    /// Listen for the `forceDeleting` event (return `false` to cancel).
    fn force_deleting<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::ForceDeleting, callback);
    }

    /// Listen for the `forceDeleted` event.
    fn force_deleted<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::ForceDeleted, callback);
    }

    /// Listen for the `trashed` event (a soft delete).
    fn soft_deleted<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Trashed, callback);
    }

    /// Listen for the `replicating` event.
    fn replicating<O: EventOutcome>(callback: impl Fn(&mut Self) -> O + Send + Sync + 'static) {
        events::listen(ModelEvent::Replicating, callback);
    }

    /// Remove every event listener and observer of the model.
    fn flush_event_listeners() {
        EloquentState::resolve().clear_listeners::<Self>();
    }

    /// Register a global scope: a constraint applied to every query for the
    /// model (remove it with `without_global_scope(name)`).
    ///
    /// ```ignore
    /// User::add_global_scope("active", |query| query.where_("active", true));
    /// ```
    fn add_global_scope(
        name: &str,
        scope: impl Fn(Builder<Self>) -> Builder<Self> + Send + Sync + 'static,
    ) {
        let state = EloquentState::resolve();
        state.boot::<Self>();
        state.add_global_scope::<Self>(name.to_string(), std::sync::Arc::new(scope));
    }

    /// Register a [`Scope`] object as a global scope (Laravel's
    /// `addGlobalScope(new AncientScope)`). It is named after its type, so
    /// `without_global_scope("AncientScope")` removes it too.
    ///
    /// ```ignore
    /// User::add_global_scope_object(AncientScope);
    /// ```
    fn add_global_scope_object<S: Scope<Self>>(scope: S) {
        let state = EloquentState::resolve();
        state.boot::<Self>();
        state.add_global_scope::<Self>(
            scope_name::<S>(),
            std::sync::Arc::new(move |query| scope.apply(query)),
        );
    }

    /// Begin a query without the given [`Scope`] object.
    fn without_global_scope_object<S: Scope<Self>>() -> Builder<Self> {
        Self::query().without_global_scope_object::<S>()
    }

    /// Determine whether the model has the named global scope.
    fn has_global_scope(name: &str) -> bool {
        let state = EloquentState::resolve();
        state.boot::<Self>();
        state
            .global_scopes::<Self>()
            .iter()
            .any(|(registered, _)| registered == name)
    }

    // ------------------------------------------------------------------
    // Route model binding
    // ------------------------------------------------------------------

    /// The value of the model's route key.
    fn route_key_value(&self) -> String {
        super::key_string(&self.get_attribute(Self::route_key_name())).unwrap_or_default()
    }

    /// Retrieve the model for a bound route parameter: `field` defaults to
    /// the route key name. Soft deleted models are excluded.
    fn resolve_route_binding(
        value: &str,
        field: Option<&str>,
    ) -> impl Future<Output = Result<Option<Self>>> + Send {
        let query = route_binding_query::<Self>(Self::query(), value, field);
        async move { query.first().await }
    }

    /// Retrieve the model for a bound route parameter, including soft
    /// deleted models (`->withTrashed()` routes).
    fn resolve_soft_deletable_route_binding(
        value: &str,
        field: Option<&str>,
    ) -> impl Future<Output = Result<Option<Self>>> + Send {
        let query = route_binding_query::<Self>(Self::query().with_trashed(), value, field);
        async move { query.first().await }
    }

    /// Retrieve the model for a bound route parameter or fail with a
    /// [`ModelNotFoundException`] (rendered as a 404).
    fn resolve_route_binding_or_fail(
        value: &str,
        field: Option<&str>,
    ) -> impl Future<Output = Result<Self>> + Send {
        let query = route_binding_query::<Self>(Self::query(), value, field);
        let value = value.to_string();
        async move {
            query.first().await?.ok_or_else(|| {
                ModelNotFoundException::new(Self::class_name(), vec![Value::String(value)]).into()
            })
        }
    }

    // ------------------------------------------------------------------
    // Attributes
    // ------------------------------------------------------------------

    /// The value of the model's primary key.
    fn get_key(&self) -> Value {
        self.get_attribute(Self::primary_key())
    }

    /// Whether the model exists in the database.
    ///
    /// A model with an [`Original`] field exists once it has been retrieved
    /// or saved (and until it is deleted). Without one, this is inferred
    /// from the key: the key is set (non-null, non-zero and non-empty), so a
    /// model whose key you assign yourself "exists" until it is saved.
    fn exists(&self) -> bool {
        match self.original_state() {
            Some(original) => original.exists,
            None => key_is_set(&self.get_key()),
        }
    }

    /// Whether the model was inserted while the current process held it
    /// (Laravel's `wasRecentlyCreated`). Always `false` for models without
    /// an [`Original`] field.
    fn was_recently_created(&self) -> bool {
        self.original_state()
            .is_some_and(|original| original.recently_created)
    }

    /// Whether the attribute may be mass assigned.
    fn is_fillable(key: &str) -> bool {
        if EloquentState::resolve().is_unguarded() || Self::fillable().contains(&key) {
            return true;
        }
        if Self::is_guarded(key) {
            return false;
        }
        Self::fillable().is_empty() && !key.contains('.') && !key.starts_with('_')
    }

    /// Whether the attribute is guarded against mass assignment.
    fn is_guarded(key: &str) -> bool {
        let guarded = Self::guarded();
        if guarded.is_empty() {
            return false;
        }
        guarded == ["*"]
            || guarded.iter().any(|g| g.eq_ignore_ascii_case(key))
            || !Self::columns().contains(&key)
    }

    /// Whether every attribute is guarded (no fillable attributes and
    /// `guarded = ["*"]`).
    fn totally_guarded() -> bool {
        Self::fillable().is_empty() && Self::guarded() == ["*"]
    }

    /// Fill the model with attributes, respecting mass assignment
    /// protection. On a totally guarded model, assigning anything fails
    /// with a [`MassAssignmentException`].
    fn fill(&mut self, attributes: impl Into<Attributes>) -> Result<&mut Self> {
        let unguarded = EloquentState::resolve().is_unguarded();
        let totally_guarded = Self::totally_guarded();
        let prevent = state::prevents_silently_discarding_attributes();
        let only_fillable = !unguarded && !Self::fillable().is_empty();
        let violation = |keys: Vec<String>| -> Result<()> {
            match state::discarded_attribute_handler() {
                Some(handler) => {
                    handler(Self::class_name(), &keys);
                    Ok(())
                }
                None => {
                    Err(MassAssignmentException::new(keys.join(", "), Self::class_name()).into())
                }
            }
        };
        let mut discarded = Vec::new();
        for (key, value) in attributes.into().0 {
            if only_fillable && !Self::fillable().contains(&key.as_str()) {
                discarded.push(key);
            } else if unguarded || Self::is_fillable(&key) {
                self.set_attribute(&key, value)?;
            } else if totally_guarded || prevent {
                violation(vec![key])?;
            }
        }
        if prevent && !discarded.is_empty() {
            violation(discarded)?;
        }
        Ok(self)
    }

    /// Get an attribute, failing with a [`MissingAttributeException`]
    /// (or calling the registered handler) when it doesn't exist or wasn't
    /// retrieved and [`prevent_accessing_missing_attributes`] is on.
    ///
    /// [`MissingAttributeException`]: super::MissingAttributeException
    /// [`prevent_accessing_missing_attributes`]: super::prevent_accessing_missing_attributes
    fn try_get_attribute(&self, key: &str) -> Result<Value> {
        let value = self.get_attribute(key);
        let missing = self
            .original_state()
            .is_some_and(|original| original.missing.iter().any(|m| m == key))
            || (value.is_null()
                && !Self::columns().contains(&key)
                && !Self::appends().contains(&key)
                && !Self::relation_names().contains(&key));
        if missing
            && self.exists()
            && !self.was_recently_created()
            && state::prevents_accessing_missing_attributes()
        {
            return match state::missing_attribute_handler() {
                Some(handler) => {
                    handler(Self::class_name(), &[key.to_string()]);
                    Ok(Value::Null)
                }
                None => Err(super::MissingAttributeException::new(Self::class_name(), key).into()),
            };
        }
        Ok(value)
    }

    // ------------------------------------------------------------------
    // Serialization visibility
    // ------------------------------------------------------------------

    /// The attributes hidden from serialization (the instance's list, after
    /// `make_hidden` / `make_visible`).
    fn get_hidden(&self) -> Vec<String> {
        self.original_state()
            .and_then(|original| original.hidden.clone())
            .unwrap_or_else(|| Self::hidden().iter().map(|h| h.to_string()).collect())
    }

    /// The attributes visible in serialization (empty means "all").
    fn get_visible(&self) -> Vec<String> {
        self.original_state()
            .and_then(|original| original.visible.clone())
            .unwrap_or_else(|| Self::visible().iter().map(|v| v.to_string()).collect())
    }

    /// Replace the instance's hidden attributes. Instance visibility lives
    /// in the model's [`Original`] field; without one this does nothing.
    fn set_hidden(&mut self, hidden: impl IntoAttributeNames) -> &mut Self {
        let hidden = hidden.into_attribute_names();
        if let Some(original) = self.original_state_mut() {
            original.hidden = Some(hidden);
        }
        self
    }

    /// Replace the instance's visible attributes (requires an [`Original`]
    /// field).
    fn set_visible(&mut self, visible: impl IntoAttributeNames) -> &mut Self {
        let visible = visible.into_attribute_names();
        if let Some(original) = self.original_state_mut() {
            original.visible = Some(visible);
        }
        self
    }

    /// Hide the given attributes on this instance (requires an [`Original`]
    /// field, where instance visibility is kept).
    ///
    /// ```ignore
    /// let array = user.make_hidden("email").to_array();
    /// ```
    fn make_hidden(&mut self, attributes: impl IntoAttributeNames) -> &mut Self {
        let mut hidden = self.get_hidden();
        for attribute in attributes.into_attribute_names() {
            if !hidden.contains(&attribute) {
                hidden.push(attribute);
            }
        }
        self.set_hidden(hidden)
    }

    /// Hide the given attributes when the condition holds.
    fn make_hidden_if(
        &mut self,
        condition: bool,
        attributes: impl IntoAttributeNames,
    ) -> &mut Self {
        if condition {
            self.make_hidden(attributes);
        }
        self
    }

    /// Make the given (normally hidden) attributes visible on this instance
    /// (requires an [`Original`] field).
    fn make_visible(&mut self, attributes: impl IntoAttributeNames) -> &mut Self {
        let attributes = attributes.into_attribute_names();
        let hidden: Vec<String> = self
            .get_hidden()
            .into_iter()
            .filter(|h| !attributes.contains(h))
            .collect();
        let mut visible = self.get_visible();
        if !visible.is_empty() {
            for attribute in &attributes {
                if !visible.contains(attribute) {
                    visible.push(attribute.clone());
                }
            }
        }
        self.set_hidden(hidden).set_visible(visible)
    }

    /// Make the given attributes visible when the condition holds.
    fn make_visible_if(
        &mut self,
        condition: bool,
        attributes: impl IntoAttributeNames,
    ) -> &mut Self {
        if condition {
            self.make_visible(attributes);
        }
        self
    }

    /// Fill the model with attributes, ignoring mass assignment protection.
    fn force_fill(&mut self, attributes: impl Into<Attributes>) -> Result<&mut Self> {
        for (key, value) in attributes.into().0 {
            self.set_attribute(&key, value)?;
        }
        Ok(self)
    }

    /// The model as JSON (its [`to_array`](Model::to_array) form).
    fn to_json(&self) -> String {
        Value::Object(self.to_array()).to_string()
    }

    /// The given attributes (and appended accessors) of the model.
    fn only(&self, attributes: impl IntoAttributeNames) -> Map<String, Value> {
        attributes
            .into_attribute_names()
            .into_iter()
            .map(|key| {
                let value = self.get_attribute(&key);
                (key, value)
            })
            .collect()
    }

    /// The model's attributes except the given ones.
    fn except(&self, attributes: impl IntoAttributeNames) -> Map<String, Value> {
        let except = attributes.into_attribute_names();
        self.to_attributes()
            .into_iter()
            .filter(|(key, _)| !except.contains(key))
            .collect()
    }

    /// The model's attributes as an array (respecting hidden / visible
    /// attributes and appends), without its relationships.
    fn attributes_to_array(&self) -> Map<String, Value> {
        let relations = Self::relation_names();
        self.to_array()
            .into_iter()
            .filter(|(key, _)| !relations.contains(&key.as_str()))
            .collect()
    }

    /// The model's loaded relationships as an array.
    fn relations_to_array(&self) -> Map<String, Value> {
        let relations = Self::relation_names();
        self.to_array()
            .into_iter()
            .filter(|(key, _)| relations.contains(&key.as_str()))
            .collect()
    }

    /// Whether two models have the same key, table and connection.
    fn is(&self, other: &Self) -> bool {
        key_is_set(&self.get_key())
            && super::key_string(&self.get_key()) == super::key_string(&other.get_key())
    }

    /// The inverse of [`is`](Model::is).
    fn is_not(&self, other: &Self) -> bool {
        !self.is(other)
    }

    // ------------------------------------------------------------------
    // Dirty tracking
    // ------------------------------------------------------------------

    /// Whether any attribute changed since the model was retrieved or last
    /// saved.
    ///
    /// Eloquent tracks changes for models with an [`Original`] field. Without
    /// one, it can't tell what changed, so every attribute is considered
    /// dirty (which is exactly what `save()` writes) and this is always
    /// `true`.
    ///
    /// ```ignore
    /// let mut user = User::find_or_fail(1).await?;
    /// assert!(!user.is_dirty());
    ///
    /// user.title = "Painter".into();
    /// assert!(user.is_dirty());
    /// ```
    fn is_dirty(&self) -> bool {
        !self.get_dirty().is_empty()
    }

    /// Whether any of the given attributes changed since the model was
    /// retrieved or last saved (Laravel's `isDirty('title')`).
    ///
    /// ```ignore
    /// user.title = "Painter".into();
    ///
    /// assert!(user.is_dirty_any("title"));
    /// assert!(!user.is_dirty_any("first_name"));
    /// assert!(user.is_dirty_any(["first_name", "title"]));
    /// ```
    fn is_dirty_any(&self, attributes: impl IntoAttributeNames) -> bool {
        has_changes(&self.get_dirty(), &attributes.into_attribute_names())
    }

    /// Whether every attribute remained the same since the model was
    /// retrieved or last saved (the inverse of [`is_dirty`](Model::is_dirty)).
    fn is_clean(&self) -> bool {
        !self.is_dirty()
    }

    /// Whether all of the given attributes remained the same (Laravel's
    /// `isClean('title')`).
    ///
    /// ```ignore
    /// user.title = "Painter".into();
    ///
    /// assert!(user.is_clean_all("first_name"));
    /// assert!(!user.is_clean_all(["first_name", "title"]));
    /// ```
    fn is_clean_all(&self, attributes: impl IntoAttributeNames) -> bool {
        !self.is_dirty_any(attributes)
    }

    /// Whether any attribute changed when the model was last saved.
    ///
    /// ```ignore
    /// user.title = "Painter".into();
    /// user.save().await?;
    ///
    /// assert!(user.was_changed());
    /// ```
    fn was_changed(&self) -> bool {
        !self.get_changes().is_empty()
    }

    /// Whether any of the given attributes changed when the model was last
    /// saved (Laravel's `wasChanged('title')`).
    fn was_changed_any(&self, attributes: impl IntoAttributeNames) -> bool {
        has_changes(&self.get_changes(), &attributes.into_attribute_names())
    }

    /// The attributes that changed since the model was retrieved or last
    /// saved, in storage format. Every attribute, for models without an
    /// [`Original`] field and for models that were never saved.
    fn get_dirty(&self) -> Map<String, Value> {
        let current = self.to_attributes();
        match self.original_state().and_then(|o| o.attributes.as_ref()) {
            None => current,
            Some(original) => current
                .into_iter()
                .filter(|(key, value)| !is_equivalent(original.get(key), value))
                .collect(),
        }
    }

    /// The attributes that changed when the model was last saved.
    fn get_changes(&self) -> Map<String, Value> {
        self.original_state()
            .map(|original| original.changes.clone())
            .unwrap_or_default()
    }

    /// The values the changed attributes had before the model was last
    /// saved.
    ///
    /// ```ignore
    /// user.update(json!({"name": "Jack"})).await?;
    ///
    /// assert_eq!(user.get_changes()["name"], json!("Jack"));
    /// assert_eq!(user.get_previous()["name"], json!("John"));
    /// ```
    fn get_previous(&self) -> Map<String, Value> {
        self.original_state()
            .map(|original| original.previous.clone())
            .unwrap_or_default()
    }

    /// The model's original attributes (as of the last retrieve or save),
    /// in storage format. Empty for models without an [`Original`] field.
    fn get_original(&self) -> Map<String, Value> {
        self.original_state()
            .and_then(|original| original.attributes.clone())
            .unwrap_or_default()
    }

    /// An attribute's original value (`Null` when unknown).
    ///
    /// ```ignore
    /// let mut user = User::find_or_fail(1).await?;
    /// user.name = "Jack".into();
    ///
    /// assert_eq!(user.get_original_attribute("name"), json!("John"));
    /// ```
    fn get_original_attribute(&self, key: &str) -> Value {
        self.original_state()
            .and_then(|original| original.attributes.as_ref())
            .and_then(|attributes| attributes.get(key).cloned())
            .unwrap_or(Value::Null)
    }

    /// Whether an attribute's current value is equivalent to its original
    /// one (Laravel's `originalIsEquivalent`).
    fn original_is_equivalent(&self, key: &str) -> bool {
        let original = self
            .original_state()
            .and_then(|original| original.attributes.as_ref());
        match (original, self.to_attributes().get(key)) {
            (Some(original), Some(current)) => is_equivalent(original.get(key), current),
            _ => false,
        }
    }

    /// Record the current attributes as the originals: the model is clean
    /// again.
    fn sync_original(&mut self) -> &mut Self {
        if self.original_state().is_some() {
            let attributes = self.to_attributes();
            if let Some(original) = self.original_state_mut() {
                original.attributes = Some(attributes);
            }
        }
        self
    }

    /// Record the current value of the given attributes as their originals.
    fn sync_original_attributes(&mut self, attributes: impl IntoAttributeNames) -> &mut Self {
        if self.original_state().is_some() {
            let mut current = self.to_attributes();
            let names = attributes.into_attribute_names();
            if let Some(original) = self.original_state_mut() {
                let originals = original.attributes.get_or_insert_with(Map::new);
                for name in names {
                    if let Some(value) = current.remove(&name) {
                        originals.insert(name, value);
                    }
                }
            }
        }
        self
    }

    /// Record the dirty attributes as the model's changes (what
    /// [`get_changes`](Model::get_changes) and
    /// [`was_changed`](Model::was_changed) report), along with their
    /// previous values.
    fn sync_changes(&mut self) -> &mut Self {
        if self.original_state().is_some() {
            let changes = self.get_dirty();
            let originals = self.get_original();
            let previous = changes
                .keys()
                .filter_map(|key| originals.get(key).map(|value| (key.clone(), value.clone())))
                .collect();
            if let Some(original) = self.original_state_mut() {
                original.changes = changes;
                original.previous = previous;
            }
        }
        self
    }

    /// Discard the attribute changes, restoring the original values.
    ///
    /// ```ignore
    /// user.name = "Jack".into();
    /// user.discard_changes()?;
    ///
    /// assert_eq!(user.name, "John");
    /// ```
    fn discard_changes(&mut self) -> Result<&mut Self> {
        let Some(originals) = self
            .original_state()
            .and_then(|original| original.attributes.clone())
        else {
            return Ok(self);
        };
        for (key, value) in originals {
            self.set_attribute(&key, value)?;
        }
        if let Some(original) = self.original_state_mut() {
            original.changes.clear();
            original.previous.clear();
        }
        Ok(self)
    }

    /// Whether the model has been soft deleted.
    fn trashed(&self) -> bool {
        Self::soft_deletes() && !self.get_attribute(Self::deleted_at_column()).is_null()
    }

    /// Clone the model into a new, unsaved instance: the key, timestamps and
    /// unique ids are reset. Fires the `replicating` event.
    fn replicate(&self) -> impl Future<Output = Result<Self>> + Send {
        self.replicate_except(&[])
    }

    /// Clone the model into a new, unsaved instance without firing the
    /// `replicating` event.
    fn replicate_quietly(&self) -> impl Future<Output = Result<Self>> + Send {
        state::without_events(self.replicate_except(&[]))
    }

    /// Clone the model into a new, unsaved instance, also resetting the
    /// given attributes.
    fn replicate_except(&self, except: &[&str]) -> impl Future<Output = Result<Self>> + Send {
        let mut clone = self.clone();
        let mut reset: Vec<String> = vec![Self::primary_key().to_string()];
        if Self::timestamps() {
            reset.push(Self::created_at_column().to_string());
            reset.push(Self::updated_at_column().to_string());
        }
        reset.extend(except.iter().map(|e| e.to_string()));
        if let Some(original) = clone.original_state_mut() {
            *original = Original::default();
        }
        async move {
            for column in reset {
                clone.set_attribute(&column, Value::Null)?;
            }
            fire(ModelEvent::Replicating, &mut clone).await?;
            Ok(clone)
        }
    }

    // ------------------------------------------------------------------
    // Persistence
    // ------------------------------------------------------------------

    /// Save the model: insert it when it doesn't exist yet, otherwise update
    /// it.
    ///
    /// Models with an [`Original`] field update only their dirty columns
    /// (and `updated_at`); when nothing changed, the `UPDATE` and the
    /// `updating` / `updated` events are skipped entirely. Other models
    /// update every persisted column but the primary key.
    ///
    /// Returns `false` when a `saving`, `creating` or `updating` listener
    /// cancelled the operation.
    fn save(&mut self) -> impl Future<Output = Result<bool>> + Send {
        save_model(self)
    }

    /// Save the model without firing any events.
    fn save_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(save_model(self))
    }

    /// Save the model inside a database transaction: if anything fails
    /// (the save, or a listener), the transaction is rolled back.
    fn save_or_fail(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            let connection = Self::get_connection();
            connection.transaction(|| save_model(self)).await
        }
    }

    /// Insert a new model, ignoring the insert when it conflicts with an
    /// existing row (SQLite / PostgreSQL `on conflict do nothing`). Returns
    /// `false` when the row was ignored. `unique_by` limits the ignored
    /// conflicts to the given unique columns.
    fn save_or_ignore(
        &mut self,
        unique_by: Option<&[&str]>,
    ) -> impl Future<Output = Result<bool>> + Send {
        let unique_by: Option<Vec<String>> =
            unique_by.map(|columns| columns.iter().map(|c| c.to_string()).collect());
        async move {
            if self.exists() {
                anyhow::bail!(illuminate_support::error::LogicException::new(
                    "Cannot use saveOrIgnore on an existing model."
                ));
            }
            if !fire(ModelEvent::Saving, self).await? {
                return Ok(false);
            }
            let saved = perform_insert_or_ignore(self, unique_by).await?;
            if saved {
                fire(ModelEvent::Saved, self).await?;
                self.sync_original();
            }
            Ok(saved)
        }
    }

    /// Save the model and every loaded related model, recursively.
    fn push(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !save_model(self).await? {
                return Ok(false);
            }
            self.push_relations().await
        }
    }

    /// Save the model and its loaded relationships without firing events.
    fn push_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(async move {
            if !save_model(self).await? {
                return Ok(false);
            }
            self.push_relations().await
        })
    }

    /// Fill the model with attributes (respecting mass assignment
    /// protection) and save it.
    fn update(
        &mut self,
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !self.exists() {
                return Ok(false);
            }
            self.fill(attributes)?;
            self.save().await
        }
    }

    /// Fill and save the model inside a database transaction.
    fn update_or_fail(
        &mut self,
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !self.exists() {
                return Ok(false);
            }
            self.fill(attributes)?;
            self.save_or_fail().await
        }
    }

    /// Fill and save the model without firing any events.
    fn update_quietly(
        &mut self,
        attributes: impl Into<Attributes> + Send,
    ) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !self.exists() {
                return Ok(false);
            }
            self.fill(attributes)?;
            self.save_quietly().await
        }
    }

    /// Update the model's `updated_at` timestamp without firing events.
    fn touch_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(async move {
            if !Self::uses_timestamps() || !Self::uses_updated_at() {
                return Ok(false);
            }
            self.set_attribute(Self::updated_at_column(), now())?;
            save_model(self).await
        })
    }

    /// Update the model's `updated_at` timestamp.
    fn touch(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !Self::uses_timestamps() || !Self::uses_updated_at() {
                return Ok(false);
            }
            self.set_attribute(Self::updated_at_column(), now())?;
            self.save().await
        }
    }

    /// Increment a column on the model's row (and in memory), touching
    /// `updated_at`.
    fn increment(
        &mut self,
        column: &str,
        amount: impl Into<Value> + Send,
    ) -> impl Future<Output = Result<u64>> + Send {
        increment_model(self, column.to_string(), amount.into(), "+")
    }

    /// Decrement a column on the model's row (and in memory), touching
    /// `updated_at`.
    fn decrement(
        &mut self,
        column: &str,
        amount: impl Into<Value> + Send,
    ) -> impl Future<Output = Result<u64>> + Send {
        increment_model(self, column.to_string(), amount.into(), "-")
    }

    /// Delete the model (a soft delete for `#[soft_deletes]` models).
    ///
    /// Returns `false` when the model doesn't exist or a `deleting` listener
    /// cancelled the operation.
    fn delete(&mut self) -> impl Future<Output = Result<bool>> + Send {
        delete_model(self, false)
    }

    /// Delete the model without firing any events.
    fn delete_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(delete_model(self, false))
    }

    /// Delete the model inside a database transaction.
    fn delete_or_fail(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !self.exists() {
                return Ok(false);
            }
            let connection = Self::get_connection();
            connection.transaction(|| delete_model(self, false)).await
        }
    }

    /// Permanently delete the model without firing any events.
    fn force_delete_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(delete_model(self, true))
    }

    /// Restore a soft deleted model without firing any events.
    fn restore_quietly(&mut self) -> impl Future<Output = Result<bool>> + Send {
        state::without_events(async move {
            if !Self::soft_deletes() {
                return Ok(false);
            }
            self.set_attribute(Self::deleted_at_column(), Value::Null)?;
            save_model(self).await
        })
    }

    /// Permanently delete the model, even when it is soft deletable.
    fn force_delete(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !Self::soft_deletes() {
                return self.delete().await;
            }
            if !fire(ModelEvent::ForceDeleting, self).await? {
                return Ok(false);
            }
            let deleted = delete_model(self, true).await?;
            if deleted {
                fire(ModelEvent::ForceDeleted, self).await?;
            }
            Ok(deleted)
        }
    }

    /// Restore a soft deleted model.
    fn restore(&mut self) -> impl Future<Output = Result<bool>> + Send {
        async move {
            if !Self::soft_deletes() {
                return Ok(false);
            }
            if !fire(ModelEvent::Restoring, self).await? {
                return Ok(false);
            }
            self.set_attribute(Self::deleted_at_column(), Value::Null)?;
            let saved = self.save().await?;
            fire(ModelEvent::Restored, self).await?;
            Ok(saved)
        }
    }

    /// Reload the model's attributes from the database, re-loading its
    /// loaded relationships.
    fn refresh(&mut self) -> impl Future<Output = Result<()>> + Send {
        async move {
            if !self.exists() {
                return Ok(());
            }
            let relations = self.loaded_relations();
            let changes = self
                .original_state()
                .map(|original| (original.changes.clone(), original.previous.clone()));
            let fresh = Self::query()
                .without_global_scopes()
                .with_trashed()
                .where_key(self.get_key())
                .use_write_pdo()
                .first_or_fail()
                .await?;
            *self = fresh;
            if let (Some((changes, previous)), Some(original)) =
                (changes, self.original_state_mut())
            {
                original.changes = changes;
                original.previous = previous;
            }
            if !relations.is_empty() {
                self.load(relations).await?;
            }
            Ok(())
        }
    }

    /// Reload the model's attributes from the database, locking its row for
    /// update (inside a transaction).
    fn refresh_for_update(&mut self) -> impl Future<Output = Result<()>> + Send {
        async move {
            if !self.exists() {
                return Ok(());
            }
            let relations = self.loaded_relations();
            let fresh = Self::query()
                .without_global_scopes()
                .with_trashed()
                .where_key(self.get_key())
                .lock_for_update()
                .first_or_fail()
                .await?;
            *self = fresh;
            if !relations.is_empty() {
                self.load(relations).await?;
            }
            Ok(())
        }
    }

    /// A fresh instance of the model from the database.
    fn fresh(&self) -> impl Future<Output = Result<Option<Self>>> + Send {
        let key = self.get_key();
        async move {
            if !key_is_set(&key) {
                return Ok(None);
            }
            Self::query()
                .without_global_scopes()
                .with_trashed()
                .where_key(key)
                .use_write_pdo()
                .first()
                .await
        }
    }

    /// Eager load relationships onto the model.
    fn load(&mut self, relations: impl IntoRelations) -> impl Future<Output = Result<()>> + Send {
        let tree = EagerSpec::tree(relations.into_relations());
        async move { load_tree(std::slice::from_mut(self), tree).await }
    }

    /// Eager load relationships that aren't loaded yet.
    fn load_missing(
        &mut self,
        relations: impl IntoRelations,
    ) -> impl Future<Output = Result<()>> + Send {
        let loaded = self.loaded_relations();
        let tree: Vec<(String, EagerSpec)> = EagerSpec::tree(relations.into_relations())
            .into_iter()
            .filter(|(name, _)| !loaded.contains(&name.as_str()))
            .collect();
        async move { load_tree(std::slice::from_mut(self), tree).await }
    }

    /// Load `{relation}_count` attributes onto the model.
    fn load_count(
        &mut self,
        relations: impl IntoRelations,
    ) -> impl Future<Output = Result<()>> + Send {
        let relations = relations.into_relations();
        async move { super::collection::load_counts(std::slice::from_mut(self), relations).await }
    }

    /// Load `{relation}_{function}_{column}` attributes (`sum`, `avg`,
    /// `min`, `max`, `count`, `exists`) onto the model.
    fn load_aggregate(
        &mut self,
        relations: impl IntoRelations,
        column: &str,
        function: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        let relations = relations.into_relations();
        let (column, function) = (column.to_string(), function.to_string());
        async move {
            super::collection::load_aggregates(
                std::slice::from_mut(self),
                relations,
                &column,
                &function,
            )
            .await
        }
    }

    /// Load `{relation}_sum_{column}` attributes onto the model.
    fn load_sum(
        &mut self,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_aggregate(relations, column, "sum")
    }

    /// Load `{relation}_avg_{column}` attributes onto the model.
    fn load_avg(
        &mut self,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_aggregate(relations, column, "avg")
    }

    /// Load `{relation}_min_{column}` attributes onto the model.
    fn load_min(
        &mut self,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_aggregate(relations, column, "min")
    }

    /// Load `{relation}_max_{column}` attributes onto the model.
    fn load_max(
        &mut self,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_aggregate(relations, column, "max")
    }

    /// Load `{relation}_exists` attributes onto the model.
    fn load_exists(
        &mut self,
        relations: impl IntoRelations,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_aggregate(relations, "*", "exists")
    }

    /// Eager load a polymorphic (`morph_to`) relationship and the given
    /// relationships of the model it points to.
    ///
    /// Rust `morph_to` relations are typed (`imageable_post`), so this loads
    /// `relation` and `relations` nested under it.
    fn load_morph(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
    ) -> impl Future<Output = Result<()>> + Send {
        let tree = EagerSpec::morph_tree(relation, relations.into_relations());
        async move { load_tree(std::slice::from_mut(self), tree).await }
    }

    /// Eager load a polymorphic relationship with relationship counts on the
    /// model it points to.
    fn load_morph_count(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_morph_aggregate(relation, relations, "*", "count")
    }

    /// Eager load a polymorphic relationship with relationship aggregates
    /// on the model it points to.
    fn load_morph_aggregate(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
        column: &str,
        function: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        let tree =
            EagerSpec::morph_aggregate_tree(relation, relations.into_relations(), column, function);
        async move { load_tree(std::slice::from_mut(self), tree).await }
    }

    /// Eager load a polymorphic relationship with relationship sums.
    fn load_morph_sum(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_morph_aggregate(relation, relations, column, "sum")
    }

    /// Eager load a polymorphic relationship with relationship averages.
    fn load_morph_avg(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_morph_aggregate(relation, relations, column, "avg")
    }

    /// Eager load a polymorphic relationship with relationship minimums.
    fn load_morph_min(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_morph_aggregate(relation, relations, column, "min")
    }

    /// Eager load a polymorphic relationship with relationship maximums.
    fn load_morph_max(
        &mut self,
        relation: &str,
        relations: impl IntoRelations,
        column: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        self.load_morph_aggregate(relation, relations, column, "max")
    }

    /// Determine whether a relationship has been loaded.
    fn relation_loaded(&self, name: &str) -> bool {
        self.loaded_relations().contains(&name)
    }

    /// A clone of the model without its loaded relationships.
    fn without_relations(&self) -> Self {
        let mut clone = self.clone();
        clone.unset_relations();
        clone
    }

    /// A clone of the model without the given loaded relationship.
    fn without_relation(&self, name: &str) -> Self {
        let mut clone = self.clone();
        clone.unset_relation(name);
        clone
    }

    // ------------------------------------------------------------------
    // Relationships
    // ------------------------------------------------------------------

    /// Define a one-to-one relationship: the related model holds a
    /// `{model}_id` foreign key.
    fn has_one<R: Model>(&self) -> HasOne<Self, R> {
        HasOne::new(
            self,
            Self::get_foreign_key(),
            Self::primary_key().to_string(),
        )
    }

    /// Define a one-to-many relationship: the related models hold a
    /// `{model}_id` foreign key.
    fn has_many<R: Model>(&self) -> HasMany<Self, R> {
        HasMany::new(
            self,
            Self::get_foreign_key(),
            Self::primary_key().to_string(),
        )
    }

    /// Define the inverse of a one-to-one or one-to-many relationship: this
    /// model holds a `{related}_id` foreign key (override it with
    /// `.foreign_key("author_id")` when the relation isn't named after the
    /// related model).
    fn belongs_to<R: Model>(&self) -> BelongsTo<Self, R> {
        BelongsTo::new(self, R::get_foreign_key(), R::primary_key().to_string())
    }

    /// Define a many-to-many relationship through a pivot table named after
    /// both models in alphabetical order (`role_user`).
    fn belongs_to_many<R: Model>(&self) -> BelongsToMany<Self, R> {
        BelongsToMany::new(self)
    }

    /// Define a has-many-through relationship: `Country` → `User` → `Post`
    /// is `self.has_many_through::<Post, User>()`.
    fn has_many_through<R: Model, T: Model>(&self) -> HasManyThrough<Self, R, T> {
        HasManyThrough::new(self)
    }

    /// Define a has-one-through relationship.
    fn has_one_through<R: Model, T: Model>(&self) -> HasOneThrough<Self, R, T> {
        HasOneThrough::new(self)
    }

    /// Define a polymorphic one-to-one relationship: the related model holds
    /// `{name}_id` and `{name}_type` columns.
    fn morph_one<R: Model>(&self, name: &str) -> MorphOne<Self, R> {
        MorphOne::morph(self, name)
    }

    /// Define a polymorphic one-to-many relationship.
    fn morph_many<R: Model>(&self, name: &str) -> MorphMany<Self, R> {
        MorphMany::morph(self, name)
    }

    /// Define a polymorphic many-to-many relationship: a `Post` has many
    /// `Tag`s through a `taggables` pivot table holding `taggable_id`,
    /// `taggable_type` and `tag_id` (`self.morph_to_many::<Tag>("taggable")`).
    fn morph_to_many<R: Model>(&self, name: &str) -> MorphToMany<Self, R> {
        BelongsToMany::new(self).morph_to_many(name)
    }

    /// Define the inverse of a polymorphic many-to-many relationship: a
    /// `Tag` has many `Post`s through `taggables`
    /// (`self.morphed_by_many::<Post>("taggable")`).
    fn morphed_by_many<R: Model>(&self, name: &str) -> MorphToMany<Self, R> {
        BelongsToMany::new(self).morphed_by_many(name)
    }

    /// Define the inverse of a polymorphic relationship, for the related
    /// type `R`: this model holds `{name}_id` and `{name}_type` columns, and
    /// only parents whose type is `R` are loaded.
    fn morph_to<R: Model>(&self, name: &str) -> MorphTo<Self, R> {
        MorphTo::morph(self, name)
    }
}

/// Models nested in a `Box` (self-referencing relationships such as
/// `parent: Option<Box<Category>>`) are models too.
impl<M: Model> Model for Box<M> {
    fn table() -> String {
        M::table()
    }
    fn class_name() -> &'static str {
        M::class_name()
    }
    fn primary_key() -> &'static str {
        M::primary_key()
    }
    fn key_type() -> KeyType {
        M::key_type()
    }
    fn incrementing() -> bool {
        M::incrementing()
    }
    fn timestamps() -> bool {
        M::timestamps()
    }
    fn uses_created_at() -> bool {
        M::uses_created_at()
    }
    fn uses_updated_at() -> bool {
        M::uses_updated_at()
    }
    fn connection_name() -> Option<&'static str> {
        M::connection_name()
    }
    fn fillable() -> &'static [&'static str] {
        M::fillable()
    }
    fn guarded() -> &'static [&'static str] {
        M::guarded()
    }
    fn hidden() -> &'static [&'static str] {
        M::hidden()
    }
    fn visible() -> &'static [&'static str] {
        M::visible()
    }
    fn appends() -> &'static [&'static str] {
        M::appends()
    }
    fn per_page() -> u64 {
        M::per_page()
    }
    fn route_key_name() -> &'static str {
        M::route_key_name()
    }
    fn soft_deletes() -> bool {
        M::soft_deletes()
    }
    fn unique_ids() -> UniqueIds {
        M::unique_ids()
    }
    fn hashed_attributes() -> &'static [&'static str] {
        M::hashed_attributes()
    }
    fn columns() -> &'static [&'static str] {
        M::columns()
    }
    fn relation_names() -> &'static [&'static str] {
        M::relation_names()
    }
    fn template() -> Self {
        Box::new(M::template())
    }
    fn to_attributes(&self) -> Map<String, Value> {
        (**self).to_attributes()
    }
    fn from_attributes(attributes: Map<String, Value>) -> Result<Self> {
        M::from_attributes(attributes).map(Box::new)
    }
    fn to_array(&self) -> Map<String, Value> {
        (**self).to_array()
    }
    fn get_attribute(&self, key: &str) -> Value {
        (**self).get_attribute(key)
    }
    fn set_attribute(&mut self, key: &str, value: Value) -> Result<()> {
        (**self).set_attribute(key, value)
    }
    fn eager_load<'a>(
        models: &'a mut [Self],
        relation: &'a str,
        spec: EagerSpec,
    ) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            let mut inner: Vec<M> = models.iter().map(|model| (**model).clone()).collect();
            M::eager_load(&mut inner, relation, spec).await?;
            for (model, loaded) in models.iter_mut().zip(inner) {
                **model = loaded;
            }
            Ok(())
        })
    }
    fn relation(name: &str) -> Option<Box<dyn DynRelation>> {
        M::relation(name)
    }
    fn loaded_relations(&self) -> Vec<&'static str> {
        (**self).loaded_relations()
    }
    fn original_state(&self) -> Option<&Original> {
        (**self).original_state()
    }
    fn original_state_mut(&mut self) -> Option<&mut Original> {
        (**self).original_state_mut()
    }
    fn unset_relation(&mut self, name: &str) {
        (**self).unset_relation(name)
    }
    fn unset_relations(&mut self) {
        (**self).unset_relations()
    }
    fn push_relations<'a>(&'a mut self) -> BoxFuture<'a, Result<bool>> {
        (**self).push_relations()
    }
    fn created_at_column() -> &'static str {
        M::created_at_column()
    }
    fn updated_at_column() -> &'static str {
        M::updated_at_column()
    }
    fn deleted_at_column() -> &'static str {
        M::deleted_at_column()
    }
    fn morph_class() -> String {
        M::morph_class()
    }
}

// ----------------------------------------------------------------------
// Persistence internals
// ----------------------------------------------------------------------

/// Whether a key value is "set": not null, zero or empty.
pub(crate) fn key_is_set(key: &Value) -> bool {
    match key {
        Value::Null => false,
        Value::Number(n) => n.as_f64() != Some(0.0),
        Value::String(s) => !s.is_empty(),
        Value::Bool(b) => *b,
        _ => true,
    }
}

/// The current time, in storage format.
pub(crate) fn now() -> Value {
    Value::String(Carbon::now().to_date_time_string())
}

/// Integer keys given as strings (route parameters, form input) are
/// compared as integers.
pub(crate) fn normalize_key<M: Model>(key: Value) -> Value {
    match (&key, M::key_type()) {
        (Value::String(s), KeyType::Int) => s.trim().parse::<i64>().map(Value::from).unwrap_or(key),
        _ => key,
    }
}

fn route_binding_query<M: Model>(
    query: Builder<M>,
    value: &str,
    field: Option<&str>,
) -> Builder<M> {
    let field = field.unwrap_or(M::route_key_name());
    let value = if field == M::primary_key() {
        normalize_key::<M>(Value::String(value.to_string()))
    } else {
        Value::String(value.to_string())
    };
    let column = query.qualify_column(field);
    query.where_(column, value)
}

async fn load_tree<M: Model>(models: &mut [M], tree: Vec<(String, EagerSpec)>) -> Result<()> {
    for (name, spec) in tree {
        M::eager_load(models, &name, spec).await?;
    }
    Ok(())
}

fn hash_attributes<M: Model>(model: &mut M) -> Result<()> {
    for attribute in M::hashed_attributes() {
        if let Value::String(value) = model.get_attribute(attribute)
            && let Some(hashed) = state::hash_value(&value)
        {
            model.set_attribute(attribute, Value::String(hashed))?;
        }
    }
    Ok(())
}

async fn save_model<M: Model>(model: &mut M) -> Result<bool> {
    if !fire(ModelEvent::Saving, model).await? {
        return Ok(false);
    }
    let tracked = model.original_state().is_some();
    let exists = if !model.exists() {
        false
    } else if tracked || M::incrementing() {
        true
    } else {
        M::get_connection()
            .table(M::table())
            .where_(M::primary_key(), model.get_key())
            .exists()
            .await?
    };
    let saved = if !exists {
        perform_insert(model).await?
    } else if tracked && !model.is_dirty() {
        // Nothing changed: Laravel skips the update (and its events).
        true
    } else {
        perform_update(model).await?
    };
    if saved {
        fire(ModelEvent::Saved, model).await?;
        model.sync_original();
    }
    Ok(saved)
}

async fn perform_insert<M: Model>(model: &mut M) -> Result<bool> {
    let key = M::primary_key();
    if !key_is_set(&model.get_key()) {
        match M::unique_ids() {
            UniqueIds::Uuid => {
                model.set_attribute(key, Value::String(Str::uuid7().to_string().to_lowercase()))?
            }
            UniqueIds::Ulid => {
                model.set_attribute(key, Value::String(Str::ulid().to_string().to_lowercase()))?
            }
            UniqueIds::None => {}
        }
    }
    if !fire(ModelEvent::Creating, model).await? {
        return Ok(false);
    }
    if M::uses_timestamps() {
        if M::uses_created_at() && model.get_attribute(M::created_at_column()).is_null() {
            model.set_attribute(M::created_at_column(), now())?;
        }
        if M::uses_updated_at() && model.get_attribute(M::updated_at_column()).is_null() {
            model.set_attribute(M::updated_at_column(), now())?;
        }
    }
    hash_attributes(model)?;

    // Null attributes are left out, so the database applies column defaults.
    let mut attributes = model.to_attributes();
    attributes.retain(|_, value| !value.is_null());
    let query = M::get_connection().table(M::table());
    if M::incrementing() && !key_is_set(attributes.get(key).unwrap_or(&Value::Null)) {
        attributes.remove(key);
        let id = query.insert_get_id_with_sequence(attributes, key).await?;
        model.set_attribute(key, Value::from(id))?;
    } else {
        query.insert(attributes).await?;
    }
    original::inserted(model);
    fire(ModelEvent::Created, model).await?;
    Ok(true)
}

/// Insert a model with `insert or ignore ... returning`, returning whether
/// the row was inserted.
async fn perform_insert_or_ignore<M: Model>(
    model: &mut M,
    unique_by: Option<Vec<String>>,
) -> Result<bool> {
    let key = M::primary_key();
    if !key_is_set(&model.get_key()) {
        match M::unique_ids() {
            UniqueIds::Uuid => {
                model.set_attribute(key, Value::String(Str::uuid7().to_string().to_lowercase()))?
            }
            UniqueIds::Ulid => {
                model.set_attribute(key, Value::String(Str::ulid().to_string().to_lowercase()))?
            }
            UniqueIds::None => {}
        }
    }
    if !fire(ModelEvent::Creating, model).await? {
        return Ok(false);
    }
    if M::uses_timestamps() {
        if M::uses_created_at() && model.get_attribute(M::created_at_column()).is_null() {
            model.set_attribute(M::created_at_column(), now())?;
        }
        if M::uses_updated_at() && model.get_attribute(M::updated_at_column()).is_null() {
            model.set_attribute(M::updated_at_column(), now())?;
        }
    }
    hash_attributes(model)?;
    let mut attributes = model.to_attributes();
    attributes.retain(|_, value| !value.is_null());
    if M::incrementing() && !key_is_set(attributes.get(key).unwrap_or(&Value::Null)) {
        attributes.remove(key);
    }
    if attributes.is_empty() {
        return Ok(true);
    }
    let unique_by: Option<Vec<&str>> = unique_by
        .as_ref()
        .map(|columns| columns.iter().map(String::as_str).collect());
    let rows = M::get_connection()
        .table(M::table())
        .insert_or_ignore_returning(attributes, &["*"], unique_by.as_deref())
        .await?;
    let Some(row) = rows.into_iter().next() else {
        return Ok(false);
    };
    if M::incrementing()
        && let Some(id) = row.get(key)
    {
        model.set_attribute(key, id.clone())?;
    }
    original::inserted(model);
    fire(ModelEvent::Created, model).await?;
    Ok(true)
}

async fn perform_update<M: Model>(model: &mut M) -> Result<bool> {
    if !fire(ModelEvent::Updating, model).await? {
        return Ok(false);
    }
    if model.original_state().is_some() {
        return perform_dirty_update(model).await;
    }
    if M::uses_timestamps() && M::uses_updated_at() {
        model.set_attribute(M::updated_at_column(), now())?;
    }
    hash_attributes(model)?;
    let mut attributes = model.to_attributes();
    attributes.remove(M::primary_key());
    if !attributes.is_empty() {
        M::get_connection()
            .table(M::table())
            .where_(M::primary_key(), model.get_key())
            .update(attributes)
            .await?;
    }
    fire(ModelEvent::Updated, model).await?;
    Ok(true)
}

/// Update only the dirty columns of a model that tracks its originals.
async fn perform_dirty_update<M: Model>(model: &mut M) -> Result<bool> {
    if M::uses_timestamps() && M::uses_updated_at() && !model.is_dirty_any(M::updated_at_column()) {
        model.set_attribute(M::updated_at_column(), now())?;
    }
    hash_attributes(model)?;
    let dirty = model.get_dirty();
    if !dirty.is_empty() {
        M::get_connection()
            .table(M::table())
            .where_(M::primary_key(), original::key_for_save_query(model))
            .update(dirty)
            .await?;
        model.sync_changes();
        fire(ModelEvent::Updated, model).await?;
    }
    Ok(true)
}

async fn delete_model<M: Model>(model: &mut M, force: bool) -> Result<bool> {
    if !model.exists() {
        return Ok(false);
    }
    if !fire(ModelEvent::Deleting, model).await? {
        return Ok(false);
    }
    let query = M::get_connection()
        .table(M::table())
        .where_(M::primary_key(), original::key_for_save_query(model));
    if M::soft_deletes() && !force {
        let time = now();
        model.set_attribute(M::deleted_at_column(), time.clone())?;
        let mut columns = Map::new();
        columns.insert(M::deleted_at_column().to_string(), time.clone());
        if M::uses_timestamps() && M::uses_updated_at() {
            model.set_attribute(M::updated_at_column(), time.clone())?;
            columns.insert(M::updated_at_column().to_string(), time);
        }
        let synced: Vec<String> = columns.keys().cloned().collect();
        query.update(columns).await?;
        model.sync_original_attributes(synced);
        fire(ModelEvent::Trashed, model).await?;
    } else {
        query.delete().await?;
        original::deleted(model);
    }
    fire(ModelEvent::Deleted, model).await?;
    Ok(true)
}

async fn increment_model<M: Model>(
    model: &mut M,
    column: String,
    amount: Value,
    sign: &str,
) -> Result<u64> {
    let amount = amount.to_f64_lossy().unwrap_or(0.0);
    if !model.exists() {
        return Ok(0);
    }
    if !fire(ModelEvent::Updating, model).await? {
        return Ok(0);
    }
    let mut extra = Map::new();
    if M::uses_timestamps() && M::uses_updated_at() {
        let time = now();
        model.set_attribute(M::updated_at_column(), time.clone())?;
        extra.insert(M::updated_at_column().to_string(), time);
    }
    let query = M::get_connection()
        .table(M::table())
        .where_(M::primary_key(), original::key_for_save_query(model));
    let delta = if amount.fract() == 0.0 {
        Value::from(amount as i64)
    } else {
        Value::from(amount)
    };
    let affected = if sign == "+" {
        query.increment_with(&column, delta, extra).await?
    } else {
        query.decrement_with(&column, delta, extra).await?
    };
    let current = model.get_attribute(&column).to_f64_lossy().unwrap_or(0.0);
    let updated = if sign == "+" {
        current + amount
    } else {
        current - amount
    };
    let updated = if updated.fract() == 0.0 {
        Value::from(updated as i64)
    } else {
        Value::from(updated)
    };
    model.set_attribute(&column, updated)?;
    model.sync_changes();
    fire(ModelEvent::Updated, model).await?;
    let mut synced = vec![column];
    if M::uses_timestamps() && M::uses_updated_at() {
        synced.push(M::updated_at_column().to_string());
    }
    model.sync_original_attributes(synced);
    Ok(affected)
}
